# Generated by Django 3.0.6 on 2020-05-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogsPost',
        ),
    ]
